### PR TITLE
Use vectorized graphics for icons

### PR DESCRIPTION
**Pull request by NotMyFault**
This PR replaces the PNG icons where applicable and allows core to override icons, in favor of sunsetting superseded PNGs, 
https://issues.jenkins.io/browse/JENKINS-66953

| Before | After |
| ----------- | ----------- |
|  |  |
|  |  |
|  |   |

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by NotMyFault** [comment]
@timja This plugin is up for adoption and according to the repository permission updater, the people with access seem to be no longer around, yet for https://github.com/jenkinsci/jenkins/pull/5778 can we get a release nevertheless?

**Comment by timja** [comment]
cc @Jochen-A-Fuerbacher

**Comment by timja** [comment]
@Jochen-A-Fuerbacher are you still maintaining this plugin?

**Comment by NotMyFault** [comment]
@timja If this plugin is actually unmaintained, I wouldn't mind adopting it to draft a release, if necessary.

**Comment by timja** [comment]
> @timja If this plugin is actually unmaintained, I wouldn't mind adopting it to draft a release, if necessary.

Please do, just send a PR to https://github.com/jenkins-infra/repository-permissions-updater/ as its flagged as adopt-this-plugin you can do it immediately

**Pull request merged**
